### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by dmtmalin** [nnseva/django-jsoneditor#17]
```
Unhandled exception in thread started by <function wrapper at 0x7f864e113938>
Traceback (most recent call last):
  File "/home/dmt/envs/hh-hrleague/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/dmt/envs/hh-hrleague/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/dmt/envs/hh-hrleague/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/dmt/envs/hh-hrleague/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/dmt/envs/hh-hrleague/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/dmt/envs/hh-hrleague/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/dmt/envs/hh-hrleague/local/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/home/dmt/envs/hh-hrleague/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/dmt/envs/hh-hrleague/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/dmt/PycharmProjects/hh-hrleague/src/hrleague/polls/admin.py", line 4, in <module>
    from hrleague.polls.forms import PollForm
  File "/home/dmt/PycharmProjects/hh-hrleague/src/hrleague/polls/forms.py", line 5, in <module>
    from jsoneditor.forms import JSONEditor
  File "/home/dmt/envs/hh-hrleague/local/lib/python2.7/site-packages/jsoneditor/forms.py", line 2, in <module>
    from django.forms.util import flatatt
ImportError: No module named util
```

Django 1.9.6, Python 2.7
`from django.forms.utils import flatatt` this correct

**Comment by nnseva** [comment]
Thanx for issue reporting, the bug has been fixed by the commit b7bfd08a87027b0d39dc9a982c2ed0b660287d2a
