### ISSUE TITLE
pypi package FileNotFound

### ISSUE THREAD

**Issue by mjhaller** [nnseva/django-jsoneditor#19]
I'm unsure if you are aware of the pypi package out there for this editor integration, but it doesn't install.  I'd rather use pypi than a git url for our dependencies.
```
$ pip install django-jsoneditor-ng`
...
Exception information:
Traceback (most recent call last):
  File "/Users/mhaller/projects/iz2/.virtualenv/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/mhaller/projects/iz2/.virtualenv/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/Users/mhaller/projects/iz2/.virtualenv/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/Users/mhaller/projects/iz2/.virtualenv/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Users/mhaller/projects/iz2/.virtualenv/lib/python2.7/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/Users/mhaller/projects/iz2/.virtualenv/lib/python2.7/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/Users/mhaller/projects/iz2/.virtualenv/lib/python2.7/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/Users/mhaller/projects/iz2/.virtualenv/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/19/xnbsch715w38r8lccwm7bsk40000gn/T/pip-build-4LvEYg/django-jsoneditor-ng/
```

When I look at setup.py in the package it is clear that README.md is not packaged.

```
try:   
        with open('README.md') as f:
            long_description = f.read()
except FileNotFoundError:
        long_description = ""
```

I'll also try to contact the package maintainer on pypi, but thought you might have some insight.  I presume that the README.md should be packaged.

@ponytech - possibly you are the maintainer (package index owner) and could fix it?

thanks to you both!

**Comment by nnseva** [comment]
Yes, I didn't publish pypi package. Please @ponytech fix your code or give me access to the package setup source code.

**Comment by mjhaller** [comment]
Haven't heard back from @ponytech, I thought I'd go ahead and make the pypi project myself.  I assume you would have no issue with that.

Also, I would pick the name django-jsoneditor.

**Comment by ladeoshodi** [comment]
Hi @nnseva 
We published the package on pypi here https://pypi.python.org/pypi/django-jsoneditor
We can now run the command below to install 
```
pip install django-jsoneditor
```

Also do you have an account on pypi? We need it to also add you as owner to that package on pypi

cc @mjhaller

**Comment by nnseva** [comment]
Hi @andela-ooshodi ,

I've registered on the pypi and my name is `nnseva` there. Please give me access to the package there to make it working.

**Comment by ladeoshodi** [comment]
Done @nnseva 

You are also an owner

**Comment by nnseva** [comment]
Nice to inform your all people that the package is now working.

```
pip install django-jsoneditor 
```

@mjhaller @andela-ooshodi
