### ISSUE TITLE
Problems with static files in Django 2.1.3

### ISSUE THREAD

**Issue by nnseva** [nnseva/django-jsoneditor#42]
```
remote:          File "/tmp/build_513f134dea38471d7da27c0fbe53f61a/api/admin.py", line 7, in <module>
remote:            from jsoneditor.forms import JSONEditor
remote:          File "/app/.heroku/python/lib/python3.7/site-packages/jsoneditor/forms.py", line 32, in <module>
remote:            class JSONEditor(Textarea):
remote:          File "/app/.heroku/python/lib/python3.7/site-packages/jsoneditor/forms.py", line 33, in JSONEditor
remote:            class Media:
remote:          File "/app/.heroku/python/lib/python3.7/site-packages/jsoneditor/forms.py", line 35, in Media
remote:            static('admin/js/vendor/jquery/jquery.js'),
remote:          File "/app/.heroku/python/lib/python3.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 19, in static
remote:            return _static(path)
remote:          File "/app/.heroku/python/lib/python3.7/site-packages/django/templatetags/static.py", line 167, in static
remote:            return StaticNode.handle_simple(path)
remote:          File "/app/.heroku/python/lib/python3.7/site-packages/django/templatetags/static.py", line 118, in handle_simple
remote:            return staticfiles_storage.url(path)
remote:          File "/app/.heroku/python/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 152, in url
remote:            return self._url(self.stored_name, name, force)
remote:          File "/app/.heroku/python/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 131, in _url
remote:            hashed_name = hashed_name_func(*args)
remote:          File "/app/.heroku/python/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 419, in stored_name
remote:            raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
remote:        ValueError: Missing staticfiles manifest entry for 'admin/js/vendor/jquery/jquery.js'
```

Django: 2.1.3
Deployed on Heroku with whitenoise

_Originally posted by @L3K0V in https://github.com/nnseva/django-jsoneditor/pull/40#issuecomment-435738857_

**Comment by azlekov** [comment]
Hey, @nnseva I saw you close with a `wontfix` but do you have any workaround for it. I tried everything  with and without strict manifest engine and whitenoise stuff without any success.

**Comment by nnseva** [comment]
> Hey, @nnseva I saw you close with a `wontfix` but do you have any workaround for it. I tried everything with and without strict manifest engine and whitenoise stuff without any success.

Hi @L3K0V, I've installed Django 2.1.3 and python 3.7 and can't reproduce the problem.

Please provide an example demonstrating an issue which I could deploy and reproduce one.

You probably could extract some minimal code from your project, as a separate project reproducing an issue.

Without an example, reproducing an issue stable, I can't search for the source of one. Whether it concerns the exact version of Django or Python? Does it appear only in heroku environment, or everywhere?

**Comment by azlekov** [comment]
I will get back to you...

**Comment by azlekov** [comment]
Below attached you can find clean app configured for Heroku with whitenoise using all latest versions and configuration.

Steps to reproduce:
```
python3 -m venv venv
pip install -r requirements.txt
python3 manage.py makemigrations
```

The issue persist also local on my machine.
If DEBUG=True everything is okay, it fails when DEBUG=False

Versions:

```
pip list
Package             Version
------------------- -------
dj-database-url     0.5.0
Django              2.1.3
django-heroku       0.3.1
django-jsoneditor   0.0.13
djangorestframework 3.9.0
gunicorn            19.9.0
Markdown            3.0.1
packaging           18.0
pip                 10.0.1
psycopg2            2.7.6.1
pyparsing           2.3.0
pytz                2018.7
setuptools          39.0.1
six                 1.11.0
whitenoise          4.1.2
```

Error:

```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/lekov/Workspace/djnago_json_editor/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/lekov/Workspace/djnago_json_editor/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/Users/lekov/Workspace/djnago_json_editor/venv/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/lekov/Workspace/djnago_json_editor/venv/lib/python3.7/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/Users/lekov/Workspace/djnago_json_editor/venv/lib/python3.7/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/Users/lekov/Workspace/djnago_json_editor/venv/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Users/lekov/Workspace/djnago_json_editor/venv/lib/python3.7/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/lekov/Workspace/djnago_json_editor/app/admin.py", line 7, in <module>
    from jsoneditor.forms import JSONEditor
  File "/Users/lekov/Workspace/djnago_json_editor/venv/lib/python3.7/site-packages/jsoneditor/forms.py", line 32, in <module>
    class JSONEditor(Textarea):
  File "/Users/lekov/Workspace/djnago_json_editor/venv/lib/python3.7/site-packages/jsoneditor/forms.py", line 33, in JSONEditor
    class Media:
  File "/Users/lekov/Workspace/djnago_json_editor/venv/lib/python3.7/site-packages/jsoneditor/forms.py", line 35, in Media
    static('admin/js/vendor/jquery/jquery.js'),
  File "/Users/lekov/Workspace/djnago_json_editor/venv/lib/python3.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 19, in static
    return _static(path)
  File "/Users/lekov/Workspace/djnago_json_editor/venv/lib/python3.7/site-packages/django/templatetags/static.py", line 167, in static
    return StaticNode.handle_simple(path)
  File "/Users/lekov/Workspace/djnago_json_editor/venv/lib/python3.7/site-packages/django/templatetags/static.py", line 118, in handle_simple
    return staticfiles_storage.url(path)
  File "/Users/lekov/Workspace/djnago_json_editor/venv/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 152, in url
    return self._url(self.stored_name, name, force)
  File "/Users/lekov/Workspace/djnago_json_editor/venv/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 131, in _url
    hashed_name = hashed_name_func(*args)
  File "/Users/lekov/Workspace/djnago_json_editor/venv/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 419, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'admin/js/vendor/jquery/jquery.js'
```

[djnago_json_editor_error.zip](https://github.com/nnseva/django-jsoneditor/files/2609064/djnago_json_editor_error.zip)

**Comment by azlekov** [comment]
@nnseva check this for reference https://github.com/jmrivas86/django-json-widget/issues/7

**Comment by azlekov** [comment]
@nnseva  Using this Media everything seems to be fixed but not sure for older versions of Django:

```
class Media:
        js = (
            'admin/js/vendor/jquery/jquery.js',
            'admin/js/jquery.init.js',
            getattr(settings, "JSON_EDITOR_JS", 'jsoneditor/jsoneditor.js'),
            'django-jsoneditor/django-jsoneditor.js',
        )
        css = {'all': (getattr(settings, "JSON_EDITOR_CSS", 'jsoneditor/jsoneditor.css'),), }
```
